// let's imagine this file is autogenerated from the backend
// ideally, we want to keep these api related types in sync
// with the backend instead of manually writing them out

export type BaseEntity = {
	id: string;
	dateCreated: Date;
};

export type Entity<T> = {
	[K in keyof T]: T[K];
} & BaseEntity;

export type Meta = {
	page: number;
	total: number;
	totalPages: number;
};

export type User = Entity<{
	firstName: string;
	lastName: string;
	email: string;
	dateOfBirth: Date,
	role: Role;
}>;

export type AuthResponse = {
	jwt: string;
	user: User;
};

export type Role = {
	abrv: string,
	name: string
}
